from __future__ import annotations

import html
import os
from datetime import datetime, timezone, timedelta
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image,
    KeepTogether,
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = ROOT / "reports" / "daily-intelligence"
ASSET_DIR = REPORT_DIR / "2026-07-03-assets"
PDF_PATH = REPORT_DIR / "2026-07-03-daily-internet-intelligence-dossier.pdf"
MD_PATH = REPORT_DIR / "2026-07-03-daily-internet-intelligence-dossier.md"


SOURCES = [
    ("S1", "Nvidia neocloud revenue-sharing plan with Sharon AI and Firmus", "Investor's Business Daily", "2026-07-03", "https://www.investors.com/news/technology/nvidia-stock-chipmaker-partners-sharon-ai-firmus/"),
    ("S2", "Nvidia revenue-sharing plan and investor reaction", "Barron's", "2026-07-03", "https://www.barrons.com/articles/nvidia-stock-price-ai-revenue-sharing-plan-c3f79c54"),
    ("S3", "AI token pricing crisis and enterprise spend pressure", "Barron's", "2026-07-03", "https://www.barrons.com/articles/ai-tokens-anthropic-openai-claude-chatgpt-b6d27e5e"),
    ("S4", "Accenture tells staff to curb unnecessary AI use amid token spend", "ITPro", "2026-06-30", "https://www.itpro.com/technology/artificial-intelligence/what-were-seeing-right-now-is-just-rapid-escalation-in-ai-token-spend-accenture-tells-staff-to-stop-using-ai-for-unnecessary-tasks-amid-surging-costs"),
    ("S5", "Mozilla 0din demo: AI coding agents tricked into malware installation", "Tom's Hardware", "2026-06-29", "https://www.tomshardware.com/tech-industry/cyber-security/ai-coding-agents-can-be-tricked-into-installing-malware-via-clean-github-repositories-mozillas-0din-team-shows-how-claude-code-can-be-exploited-by-its-own-helpfulness"),
    ("S6", "The Shift to Agentic AI: Evidence from Codex", "arXiv", "2026-06-25", "https://arxiv.org/abs/2606.26959"),
    ("S7", "How Do AI Agents Spend Your Money?", "arXiv", "2026-04-24", "https://arxiv.org/abs/2604.22750"),
    ("S8", "Where Do AI Coding Agents Fail?", "arXiv", "2026-01-21", "https://arxiv.org/abs/2601.15195"),
    ("S9", "Phoenix: Safe GitHub Issue Resolution via Multi-Agent LLMs", "arXiv", "2026-06-18", "https://arxiv.org/abs/2606.20243"),
    ("S10", "Understanding rejection of fixes generated by agentic PRs", "arXiv", "2026-06-11", "https://arxiv.org/abs/2606.13468"),
    ("S11", "RBI draft model risk framework and AI kill switch coverage", "Economic Times", "2026-06-24", "https://m.economictimes.com/industry/banking/finance/banking/rbi-mandates-kill-switch-for-ai-models-at-banks-introduces-comprehensive-model-risk-framework/articleshow/131969198.cms"),
    ("S12", "EU General-Purpose AI Code of Practice overview", "European Commission", "2025-07-10", "https://digital-strategy.ec.europa.eu/en/policies/contents-code-gpai"),
    ("S13", "EU AI Office role and AI Act implementation", "European Commission", "2024-2026", "https://digital-strategy.ec.europa.eu/en/policies/ai-office"),
    ("S14", "Transparency as Architecture: EU AI Act Article 50 II", "arXiv", "2026-03-27", "https://arxiv.org/abs/2603.26983"),
    ("S15", "India DPDP Rules 2025 overview", "MeitY / public summary", "2025-11-14", "https://www.meity.gov.in/"),
    ("S16", "Biomedical data policy framework for Indian healthcare AI", "arXiv", "2026-04-13", "https://arxiv.org/abs/2604.11125"),
    ("S17", "OpenAI unveils GPT-5.6 amid regulatory drama", "The Verge", "2026-06-27", "https://www.theverge.com/ai-artificial-intelligence/957845/openai-gpt-5-6-trump-administration-ai-preview"),
    ("S18", "Product Hunt AI launches feed", "Product Hunt", "2026-07-03", "https://www.producthunt.com/"),
    ("S19", "GitHub Trending repositories", "GitHub", "2026-07-03", "https://github.com/trending"),
    ("S20", "Hacker News front page and discussion scan", "Hacker News", "2026-07-03", "https://news.ycombinator.com/"),
]


def esc(text: str) -> str:
    return html.escape(text, quote=False)


def link(label: str, url: str) -> str:
    return f'<link href="{html.escape(url, quote=True)}" color="#0969da">{esc(label)}</link>'


def sid(source_id: str) -> str:
    source = next(s for s in SOURCES if s[0] == source_id)
    return link(f"[{source_id}]", source[4])


def make_styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], fontName="Helvetica-Bold", fontSize=27, leading=32, textColor=colors.HexColor("#17202a"), alignment=TA_CENTER, spaceAfter=10),
        "subtitle": ParagraphStyle("subtitle", parent=base["BodyText"], fontSize=11.5, leading=16, textColor=colors.HexColor("#39424e"), alignment=TA_CENTER, spaceAfter=16),
        "h1": ParagraphStyle("h1", parent=base["Heading1"], fontName="Helvetica-Bold", fontSize=18, leading=22, textColor=colors.HexColor("#12343b"), spaceBefore=16, spaceAfter=8),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=13.5, leading=17, textColor=colors.HexColor("#24505a"), spaceBefore=10, spaceAfter=6),
        "body": ParagraphStyle("body", parent=base["BodyText"], fontSize=9.6, leading=13.4, textColor=colors.HexColor("#20272e"), spaceAfter=6),
        "small": ParagraphStyle("small", parent=base["BodyText"], fontSize=8.4, leading=11.4, textColor=colors.HexColor("#4a5560"), spaceAfter=4),
        "caption": ParagraphStyle("caption", parent=base["BodyText"], fontSize=7.8, leading=10, textColor=colors.HexColor("#667085"), alignment=TA_CENTER, spaceAfter=8),
        "table": ParagraphStyle("table", parent=base["BodyText"], fontSize=7.6, leading=9.4, textColor=colors.HexColor("#20272e")),
    }


def p(text: str, style: str = "body"):
    return Paragraph(text, STYLES[style])


def bullets(items):
    return ListFlowable([ListItem(p(item), leftIndent=12) for item in items], bulletType="bullet", leftIndent=14, bulletFontSize=7)


def table(rows, widths=None, header=True):
    data = [[Paragraph(str(cell), STYLES["table"]) for cell in row] for row in rows]
    t = Table(data, colWidths=widths, repeatRows=1 if header else 0, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e6f0f2") if header else colors.white),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#12343b")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#c9d4da")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafb")]),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def section_image(name: str):
    path = ASSET_DIR / name
    img = Image(str(path), width=6.55 * inch, height=3.65 * inch)
    return KeepTogether([img, p(f"Generated visual, created with image-generation skill: {path.name}", "caption")])


def story():
    s = []
    s.extend([
        Spacer(1, 0.2 * inch),
        p("Daily Internet Intelligence Dossier", "title"),
        p("For Aman | Friday, 3 July 2026 | India builder lens, global ambition", "subtitle"),
        section_image("cover-generated.png"),
        p("<b>Thesis of the day:</b> AI is moving from capability theater to operational accounting. Compute supply is being financialized, token spend is becoming a board-level constraint, and regulators are translating AI risk into kill switches, audit trails, and provenance obligations. The hidden opportunity is not another wrapper; it is infrastructure that makes AI work measurable, governed, and affordable for teams that cannot hire a platform group. For Aman, the highest-leverage move today is to validate one narrow pain: agent cost/risk control for Indian SMBs, fintechs, dev agencies, or healthcare operators.", "body"),
        PageBreak(),
    ])

    s.extend([
        p("1. Executive Dashboard", "h1"),
        table([
            ["Rank", "Thing Aman Must Know", "Builder Meaning", "Score"],
            ["1", f"Nvidia is pushing revenue-sharing/credit support with neoclouds, including Sharon AI and Firmus. {sid('S1')} {sid('S2')}", "Compute access is becoming a financing product. Startups may buy GPU minutes through bundled infra/credit contracts instead of raw cloud accounts.", "Opp 9 / Risk 6"],
            ["2", f"AI token spend is now a serious enterprise constraint. {sid('S3')} {sid('S4')}", "Enterprises want metering, budgets, ROI attribution, and cheaper-routing systems before broad agent rollout.", "Opp 10 / Risk 7"],
            ["3", f"Agent security failures are no longer hypothetical; clean-looking repos can manipulate coding agents into unsafe execution. {sid('S5')}", "Every agent that can run commands needs preflight scanning, policy gates, least privilege, and audit trails.", "Opp 9 / Risk 9"],
            ["4", f"Codex usage evidence shows agentic work is shifting outside developer-only use. {sid('S6')}", "The market is expanding from dev tools into operations, finance, research, and knowledge work.", "Opp 8 / Risk 5"],
            ["5", f"Agent token use is highly variable and can be 1000x code chat. {sid('S7')}", "Price unpredictability is itself a product gap: forecast, cap, simulate, and explain costs before execution.", "Opp 10 / Risk 8"],
            ["6", f"AI PR failure research shows agents waste reviewer time on wrong paths, CI failures, duplicates, and low-priority fixes. {sid('S8')} {sid('S10')}", "Aman can build review triage and repo-specific guardrails, not just code generation.", "Opp 8 / Risk 6"],
            ["7", f"RBI's model-risk direction points toward kill switches, board accountability, third-party model oversight, bias/explainability controls. {sid('S11')}", "Indian BFSI vendors need model inventories and override workflows before AI procurement scales.", "Opp 9 / Risk 8"],
            ["8", f"EU AI Act transparency/GPAI obligations keep moving from policy into engineering work. {sid('S12')} {sid('S13')} {sid('S14')}", "Compliance will require architecture: provenance, labeling, training-data summaries, incident logs.", "Opp 7 / Risk 8"],
            ["9", f"India DPDP compliance plus AI adoption makes consent, deletion, and breach workflows a go-to-market wedge. {sid('S15')}", "Privacy ops for AI-enabled SMBs remains under-served and painfully manual.", "Opp 8 / Risk 7"],
            ["10", f"Indian healthcare AI remains blocked by fragmented, low-incentive biomedical data sharing. {sid('S16')}", "Data stewardship, federation, audit, and quality tooling may be better wedges than model building.", "Opp 7 / Risk 6"],
        ], [0.38*inch, 2.05*inch, 2.95*inch, 0.78*inch]),
        p("<b>Opportunity score:</b> 8.7/10. <b>Risk score:</b> 7.2/10. <b>Action score:</b> 9/10 because several pains can be validated today by talking to buyers, not by training models.", "body"),
    ])

    s.extend([
        p("2. Calendar and Personal Operating Context", "h1"),
        p("<b>Status:</b> calendar access was unavailable in this automation environment and was intentionally not checked per instruction. No private commitments, travel buffers, or meeting prep were inferred.", "body"),
        table([
            ["Today’s operating stance", "Concrete implication"],
            ["One priority", "Pick one wedge: agent cost/risk ledger for Indian dev agencies and regulated SMBs."],
            ["Avoid", "Do not chase a generic AI news app, agent marketplace, or model wrapper unless it owns a measurable operational pain."],
            ["Prep", "Draft 8 discovery questions for CTOs/founders using Claude Code, Codex, Cursor, Replit, Lovable, or internal AI workflows."],
            ["Risk", "A day of passive scanning can masquerade as work. Convert the dossier into calls, landing page copy, and one prototype screen."],
        ], [2.0*inch, 4.2*inch]),
    ])

    s.extend([
        PageBreak(),
        p("3. The World Changed Overnight", "h1"),
        section_image("compute-generated.png"),
        bullets([
            f"<b>Compute is being packaged as structured finance.</b> Nvidia's neocloud model suggests suppliers want recurring participation in usage revenue, not only chip sales. {sid('S1')} {sid('S2')} <i>Inference:</i> GPU scarcity is becoming a distribution channel for startups that can sell utilization, not own infrastructure.",
            f"<b>AI spend is becoming a governance problem.</b> Token billing, agent loops, and reasoning traces make cost hard to forecast. {sid('S3')} {sid('S7')} The buyer pain is not just expensive models; it is unpredictable variance.",
            f"<b>Enterprise AI adoption is hitting the CFO.</b> Accenture-like constraints on casual AI use show a buyer shift from 'enable everyone' to 'meter everything'. {sid('S4')} This benefits tools that connect AI usage to business outcomes.",
            f"<b>Security and compliance are converging.</b> Agent command execution, RBI kill switches, and EU provenance obligations all point to runtime controls. {sid('S5')} {sid('S11')} {sid('S14')}",
        ]),
        p("<b>Second-order effect:</b> Smaller companies will not stop adopting AI; they will outsource discipline. This creates a market for lightweight AI FinOps, policy-as-code, agent permissions, and audit packages sold in plain language.", "body"),
    ])

    s.extend([
        p("4. AI Frontier Watch", "h1"),
        table([
            ["Signal", "Fact / evidence", "Builder interpretation"],
            ["Agent adoption", f"Codex usage research reports rapid growth and broader-than-developer adoption. {sid('S6')}", "Agents are moving from IDE novelty into general workplace automation. Vertical workflow data matters more than generic chat UI."],
            ["Cost frontier", f"Agentic tasks can consume orders of magnitude more tokens than ordinary coding chat, with high run-to-run variance. {sid('S7')}", "Before-action cost prediction and caps are missing primitives."],
            ["Safety frontier", f"Phoenix uses layered controls, baseline tests, and state machines to improve issue resolution safety. {sid('S9')}", "The winning products will combine autonomy with constraints, not autonomy alone."],
            ["Failure frontier", f"Studies of agent PRs show CI failures, wrong approaches, poor prioritization, and review waste. {sid('S8')} {sid('S10')}", "Agent managers need triage, scope reduction, test-first workflows, and reviewer-load accounting."],
            ["Model access", f"Recent GPT-5.6 coverage emphasized staged access, monitoring, and regulatory scrutiny. {sid('S17')}", "Frontier access is a compliance relationship. Builders should plan for multi-model routing and capability tiers."],
        ], [1.05*inch, 2.45*inch, 2.7*inch]),
    ])

    s.extend([
        p("5. AI Giants Pulse", "h1"),
        bullets([
            f"<b>Nvidia:</b> strongest current signal is not a chip benchmark; it is a business-model shift toward neocloud financing and revenue participation. {sid('S1')} {sid('S2')}",
            f"<b>OpenAI:</b> public coverage around GPT-5.6 centers on staged deployment and regulatory review, reinforcing the access-governance theme. {sid('S17')}",
            f"<b>Anthropic / coding-agent ecosystem:</b> the live risk is not only model behavior; it is agent tooling that follows repo instructions into dangerous execution paths. {sid('S5')}",
            f"<b>GitHub / open source:</b> public trending and repo ecosystems remain useful but noisy. Today’s stronger signal comes from research on agent PR outcomes and operational failures. {sid('S8')} {sid('S19')}",
            f"<b>Product-launch communities:</b> AI launches remain abundant, but the durable pain is customer trust, integration, and cost control rather than another prompt surface. {sid('S18')} {sid('S20')}",
        ]),
        p("<b>Contrarian read:</b> labs are not the only strategic actors. CFOs, CISOs, compliance officers, cloud resellers, and data-center financiers now shape what AI products can actually be bought.", "body"),
    ])

    s.extend([
        PageBreak(),
        p("6. Regulation and Policy Radar", "h1"),
        section_image("governance-generated.png"),
        table([
            ["Policy signal", "Affected users", "Founder implication", "Timeline / urgency"],
            ["RBI model-risk controls and kill-switch expectation", f"Banks, NBFCs, fintech vendors, AI vendors selling into regulated finance. {sid('S11')}", "Build model inventory, override, third-party risk, explainability, and bias-test templates.", "Immediate procurement concern in India BFSI."],
            ["EU GPAI Code / AI Office enforcement path", f"Foundation model providers and downstream deployers that touch EU markets. {sid('S12')} {sid('S13')}", "Compliance evidence becomes a product feature. Exportable audit logs matter.", "High. Enforcement and deadlines shape enterprise buying."],
            ["AI content transparency architecture", f"Generated content systems, media workflows, synthetic data platforms. {sid('S14')}", "Post-hoc watermarking is weak. Provenance should be designed into workflow state.", "Rising through 2026 obligations."],
            ["India DPDP operationalization", f"Any Indian product processing personal data, especially AI apps collecting documents, chats, voice, or health/finance records. {sid('S15')}", "Consent, deletion, breach, child-data handling, and data processing maps are sellable painkillers.", "Ongoing compliance workload."],
        ], [1.3*inch, 1.65*inch, 2.1*inch, 1.15*inch]),
        p("<b>Risk:</b> compliance theater will be common. The wedge is practical artifacts: model register, DPIA-style questionnaire, kill-switch runbook, agent execution log, vendor-risk packet, and deletion workflow.", "body"),
    ])

    s.extend([
        p("7. Community Pain Map", "h1"),
        table([
            ["Pain signal", "Observed / inferred evidence", "Opportunity"],
            ["Token bill shock", f"Media and research both point to cost unpredictability and agent spend blowouts. {sid('S3')} {sid('S4')} {sid('S7')}", "AI spend simulator, per-agent budget caps, prompt/trace compression, model-router policies."],
            ["Unsafe repo execution", f"Mozilla 0din-style exploit coverage shows agents can be socially engineered through project instructions. {sid('S5')}", "Preflight scanner for repos before agent work; command-risk classifier; secrets/session protection checklist."],
            ["Low-quality agent PRs", f"Research finds wrong approaches, CI failures, and review waste. {sid('S8')} {sid('S10')}", "Repo-specific agent playbooks, PR risk scores, review-time estimator, agent task triage."],
            ["Regulated AI uncertainty", f"RBI/EU/DPDP signals are hard for small teams to translate into engineering tasks. {sid('S11')} {sid('S12')} {sid('S15')}", "Compliance templates and evidence capture for small vendors selling to banks or EU customers."],
            ["Data fragmentation in Indian healthcare", f"Biomedical AI paper frames India’s barrier as incentive/data stewardship, not just model quality. {sid('S16')}", "Data-quality audit kits, federated dataset agreements, stewardship dashboards for hospitals/academia."],
        ], [1.35*inch, 2.55*inch, 2.3*inch]),
    ])

    s.extend([
        p("8. Market and Money Signals", "h1"),
        bullets([
            f"<b>Neoclouds become strategic buyers:</b> Sharon AI and Firmus-style deals imply AI infra startups will increasingly sell utilization-backed compute packages. {sid('S1')} For Aman: build tools that help GPU renters prove utilization, compliance, and unit economics to customers.",
            f"<b>AI FinOps is moving downmarket:</b> token spend is no longer only a hyperscaler problem. {sid('S3')} {sid('S4')} Indian dev agencies and SMB SaaS firms will need a cheaper, simple 'AI expense control' dashboard.",
            f"<b>Security products can ride agent adoption:</b> 0din-style attacks create a new category: agent endpoint security. {sid('S5')} The buyer is any team letting AI run shell commands or browser sessions.",
            f"<b>Regulated sectors will buy evidence:</b> RBI and DPDP pressures create demand for documentation, not just automation. {sid('S11')} {sid('S15')}",
        ]),
    ])

    s.extend([
        PageBreak(),
        p("9. Technical Opportunity Map", "h1"),
        table([
            ["Technical primitive", "Why it matters", "Productizable angle"],
            ["Token-cost prediction", f"Agents underestimate or vary in token consumption; more cost does not guarantee accuracy. {sid('S7')}", "Pre-run estimator, task class classifier, budget-aware agent wrapper."],
            ["Baseline-aware tests", f"Phoenix shows layered safety and baseline comparisons improve issue workflows. {sid('S9')}", "GitHub app that refuses agent PRs without baseline/test evidence."],
            ["Agent PR taxonomy", f"Failure studies identify rejection categories and review friction. {sid('S8')} {sid('S10')}", "Reviewer assistant that says whether a task is agent-suitable before spending compute."],
            ["Runtime permission gates", f"0din exploit demonstrates the danger of blindly following repo instructions. {sid('S5')}", "Policy engine: deny network/secrets/shell unless scoped and logged."],
            ["Provenance architecture", f"Article 50 analysis says transparency requires architecture, not labels pasted at the end. {sid('S14')}", "SDK for provenance events across AI content pipelines."],
        ], [1.45*inch, 2.45*inch, 2.3*inch]),
    ])

    s.extend([
        p("10. Personal Impact Analysis for Aman", "h1"),
        table([
            ["Dimension", "Positive effect", "Negative effect / threat", "What to do"],
            ["Founder timing", "Market pain is concrete and budget-linked.", "Big vendors may bundle cost controls into platforms.", "Win by verticalizing: India BFSI vendors, dev shops, or healthcare ops."],
            ["India angle", "RBI/DPDP create local urgency and trust-based selling.", "Compliance buyers move slowly.", "Start with templates + audits + small paid pilots, not a broad platform."],
            ["Skill gap", "You can prototype with existing agents and docs quickly.", "Security/compliance claims need precision.", "Interview a CISO/compliance consultant before marketing hard claims."],
            ["Distribution", "Pain can be surfaced through LinkedIn, founder WhatsApp groups, dev agencies, fintech communities.", "Generic AI content is saturated.", "Publish a sharp teardown: 'How much did your coding agent cost last sprint?'"],
            ["Ignore today", "Model leaderboard drama without pricing/access/security impact.", "Can consume attention with no product insight.", "Track only when it changes buyer behavior."],
        ], [1.05*inch, 1.55*inch, 1.7*inch, 1.9*inch]),
    ])

    ideas = [
        ["Agent Spend Ledger", "CTOs/dev agencies using Codex/Claude/Cursor", "Token variance + CFO pressure", "Chrome/CLI wrapper that logs task, model, tokens, outcome, human review time", "$49/team/mo + usage", "Ask 10 teams for last 5 painful AI bills; build CSV importer today"],
        ["Repo Agent Firewall", "Teams letting agents run shell commands", "0din malware pattern", "Preflight repo scan + command approval policy + secrets warning", "$99/repo/mo", "Record a demo scanning three public repos for risky instructions"],
        ["RBI AI Model Register Kit", "Fintech vendors, NBFC tech teams", "RBI kill-switch/model-risk direction", "Spreadsheet + web app for model inventory, owner, vendor, override, tests", "₹25k setup + SaaS", "DM 15 fintech compliance leads with a one-page checklist"],
        ["AI PR Triage Bot", "Open-source maintainers and engineering managers", "Agent PR rejection research", "Label tasks as agent-suitable, risky, duplicate, needs human", "$20/user/mo or GitHub app", "Build GitHub issue classifier for one repo"],
        ["DPDP Consent Ops for AI Apps", "Indian SMB SaaS and AI document tools", "DPDP operational burden", "Consent notice, deletion workflow, breach log, data map templates", "₹10k-₹50k setup", "Turn one AI app privacy flow into a teardown post"],
        ["AI Usage ROI Auditor", "Services firms rolling out AI internally", "Accenture-style spend controls", "Connect usage logs to task category and business outcome", "Consulting + SaaS", "Interview ops heads on what AI usage they would cut first"],
        ["Healthcare Data Stewardship Toolkit", "Indian hospitals/research groups", "Fragmented biomedical data incentives", "Data-quality scoring, audit trail, de-identification checklist", "Pilot grants + institutional SaaS", "Talk to one hospital IT/admin contact"],
    ]
    s.extend([
        PageBreak(),
        p("11. Billion-Dollar Problem Radar", "h1"),
        section_image("india-msme-generated.png"),
        table([["Idea", "Customer", "Evidence", "Wedge MVP", "Pricing", "48-hour validation"]] + ideas, [0.9*inch, 1.0*inch, 1.1*inch, 1.45*inch, 0.75*inch, 1.0*inch]),
        p("<b>Best single bet today:</b> Agent Spend Ledger + Repo Agent Firewall as one narrow product: 'Know what your coding agents cost and stop them from doing dangerous things.' It combines CFO pain, CISO fear, and developer workflow urgency.", "body"),
    ])

    s.extend([
        p("12. Micro-Opportunities", "h1"),
        bullets([
            "CLI script that estimates agent task cost from repo size, issue type, and test suite size.",
            "Lead magnet: RBI model-risk checklist for AI vendors selling to Indian banks.",
            "Browser extension that warns when a web AI agent is about to submit payment, personal data, or irreversible changes.",
            "GitHub Action that blocks agent PRs missing test logs, reproduction notes, and affected-file rationale.",
            "Notion/Sheets template: AI vendor register for DPDP/RBI-ready procurement.",
            "Public dataset of agent PR rejection examples, classified by failure reason.",
            "Landing page calculator: 'Your hidden AI token burn per developer per month.'",
            "Short course for Indian founders: AI compliance artifacts that buyers ask for.",
            "Open-source repo instruction sanitizer for AGENTS.md, CLAUDE.md, README, package scripts.",
            "Newsletter/content series: 'AI FinOps for small teams' with teardown screenshots.",
        ]),
    ])

    s.extend([
        p("13. Contrarian Corner", "h1"),
        table([
            ["Contrarian take", "Reasoning", "Uncertainty"],
            ["The next valuable AI wrapper may be an accounting wrapper.", "When token variance and agent autonomy become budget risks, the wrapper that measures, caps, and justifies usage may own purchasing power.", "Large platforms could bundle enough of this to reduce standalone value."],
            ["Regulation can accelerate small vendors, not only slow them.", "RBI/DPDP/EU rules create procurement checklists. A small vendor with clean evidence can beat a larger but opaque competitor.", "Only true if the vendor picks a narrow regulated workflow."],
            ["More autonomous agents may reduce trust before they increase productivity.", "Security exploits, PR rejection, and unpredictable spend make unsupervised autonomy hard to defend.", "Better sandboxing and model improvements could reverse this quickly."],
        ], [1.35*inch, 3.45*inch, 1.4*inch]),
    ])

    s.extend([
        p("14. Watchlist", "h1"),
        bullets([
            f"Nvidia neocloud/credit-support deals and any customer-side default or utilization stress. {sid('S1')} {sid('S2')}",
            f"EU AI Office guidance, GPAI signatories, transparency implementation standards. {sid('S12')} {sid('S13')} {sid('S14')}",
            f"RBI finalization of model-risk controls and reactions from banks/NBFCs. {sid('S11')}",
            f"Agent PR research datasets and GitHub platform changes around AI-authored PR labeling. {sid('S8')} {sid('S10')} {sid('S19')}",
            f"Mozilla 0din and similar agent security disclosures. {sid('S5')}",
            f"Enterprise memos or earnings calls mentioning AI token spend, usage caps, or productivity audit. {sid('S3')} {sid('S4')}",
        ]),
    ])

    s.extend([
        PageBreak(),
        p("15. Today’s Action Plan", "h1"),
        section_image("action-plan-generated.png"),
        table([
            ["Time box", "Action", "Output"],
            ["15 min", "Write a one-line ICP: 'Indian dev agencies/fintech vendors using AI coding agents but lacking cost and risk controls.'", "A clear target customer."],
            ["15 min", "Create a 6-question discovery form on AI agent spend, review waste, scary command execution, and compliance worries.", "Shareable survey link or doc."],
            ["15 min", "Post a LinkedIn/X prompt: 'Did your AI coding agent save time but spike token spend or review load? I’m collecting examples.'", "Inbound anecdotes."],
            ["1 hour", "Mock one dashboard screen: task, model, tokens, approval, risk flags, tests run, human review outcome.", "Prototype artifact for calls."],
            ["1 hour", "Scan one real repo for agent-danger patterns: install scripts, remote curl, secrets, malicious instructions, ambiguous setup docs.", "Demo material."],
            ["Deep work", "Build a CSV-first MVP: import agent logs, classify task, estimate cost, flag runaway sessions.", "Usable internal tool."],
            ["Deep work", "Draft RBI/DPDP model inventory template and offer it to 5 fintech founders.", "Lead magnet + buyer signal."],
        ], [0.8*inch, 4.2*inch, 1.2*inch]),
    ])

    s.extend([
        p("16. Methodology and Limitations", "h1"),
        p("Scanned accessible web search results, official/public sources where reachable, current news snippets, arXiv papers, GitHub/Product Hunt/Hacker News entry points, and prior automation memory. Calendar access was unavailable and intentionally skipped. Login-gated X/Twitter, private Discords, paid-only articles, and private newsletters were not accessed; where only secondary reporting was available, the dossier labels the source type and avoids treating unavailable private material as fact.", "body"),
        p("Facts are tied to sources. Analysis and product implications are explicitly inferential. Startup ideas are hypotheses for validation, not claims of guaranteed demand.", "body"),
    ])

    s.extend([
        p("17. Source Appendix", "h1"),
    ])
    for source_id, title, publisher, date, url in SOURCES:
        s.append(p(f"<b>{source_id}.</b> {esc(title)}. {esc(publisher)}, {esc(date)}. {link(url, url)}", "small"))
    return s


def write_markdown():
    lines = [
        "# Daily Internet Intelligence Dossier",
        "",
        "For Aman | Friday, 3 July 2026",
        "",
        "Generated visuals used in PDF:",
        *[f"- {path.name}: {path}" for path in sorted(ASSET_DIR.glob("*.png"))],
        "",
        "## Thesis",
        "AI is moving from capability theater to operational accounting. Compute supply is being financialized, token spend is becoming a board-level constraint, and regulators are translating AI risk into kill switches, audit trails, and provenance obligations. The hidden opportunity is infrastructure that makes AI work measurable, governed, and affordable.",
        "",
        "## Top actions",
        "1. Validate an Agent Spend Ledger with 10 Indian/global dev teams.",
        "2. Prototype a Repo Agent Firewall scan for risky repo instructions and command execution.",
        "3. Publish a sharp teardown on hidden AI token burn and review waste.",
        "4. Turn RBI/DPDP requirements into a model-register lead magnet for fintech vendors.",
        "",
        "## Sources",
    ]
    for source_id, title, publisher, date, url in SOURCES:
        lines.append(f"- [{source_id}] {title}. {publisher}, {date}. {url}")
    MD_PATH.write_text("\n".join(lines), encoding="utf-8")


def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#667085"))
    canvas.drawString(0.55 * inch, 0.35 * inch, "Daily Internet Intelligence Dossier | Generated for Aman | 2026-07-03")
    canvas.drawRightString(A4[0] - 0.55 * inch, 0.35 * inch, str(doc.page))
    canvas.restoreState()


def build_pdf():
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(PDF_PATH),
        pagesize=A4,
        rightMargin=0.48 * inch,
        leftMargin=0.48 * inch,
        topMargin=0.48 * inch,
        bottomMargin=0.52 * inch,
        title="2026-07-03 Daily Internet Intelligence Dossier",
        author="Codex",
    )
    doc.build(story(), onFirstPage=on_page, onLaterPages=on_page)


if __name__ == "__main__":
    STYLES = make_styles()
    write_markdown()
    build_pdf()
    print(PDF_PATH)
    print(MD_PATH)
